name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "src\AJUpdateWatcher.sln"
    - name: Build
      run: dotnet build "src\AJUpdateWatcher.sln" --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal "src\AJUpdateWatcher.sln"
